version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn test

workflows:
  version: 2.1

  gostack11-api-dev:
    jobs:
      - build
        filters:
          branches:
            ignore:
              - master
      - test
        requires:
          - build
